### ISSUE TITLE
Improve editor 

### ISSUE THREAD

**Issue by jmatsushita** [ImaginationForPeople/assembl#11]
Would be useful for the Landing page to allow using markdown instead of wysiwyg (for the Context, Discussion objectives,...) and maybe elsewhere.

**Comment by jmatsushita** [comment]
Would also be great to be able to add images in the discussion context and objectives.

**Comment by benoitg** [comment]
This isn't going to happen, we are cutting our losses after spending way, way too many resources on the context page.  If we improve on it, it will be to allow including an IFrame as the context page.
