### ISSUE TITLE
Unauthorized message for anonymous user

### ISSUE THREAD

**Issue by jmatsushita** [ImaginationForPeople/assembl#13]
I assume this is a permission problem, but when copy pasting the discussion link into another browser to test submitting content with another user, I got the following popup:

```
Assembl has encountered a problem and needs to be refreshed. Do not worry, any messages that are in the process of being composed will not be lost.

See you in a minute on Assembl!

If you are in contact with the technical team, please let them know about the following message:

url: /data/Discussion/1/user_ns_kv/tour_seen ajax error message: Unauthorized
```

**Comment by maparent** [comment]
Are you on develop or master?

**Comment by jmatsushita** [comment]
I'm on develop (seems that's the default branch as I didn't qualify my git clone).

**Comment by jmatsushita** [comment]
I have an update though, which is that after properly adding the permission for the user to take part in the discussion the message went away. So I 'm changing the title of the issue to make it about the error message.

**Comment by maparent** [comment]
right. We try to keep develop runnable, but some of us are more careful than others (speaking as one of the guilty parties.)

**Comment by jmatsushita** [comment]
I need our discussions to be publicly accessible. However even when connecting to a discussion without being logged in, I get the error above.

![image](https://cloud.githubusercontent.com/assets/356097/9540489/8e8a9824-4d5f-11e5-9c9a-22e8aff29569.png)


These are my permissions on this discussion:

![image](https://cloud.githubusercontent.com/assets/356097/9540493/a5e72ae6-4d5f-11e5-90ee-dd46277dd6b8.png)

**Comment by swergas** [comment]
This bug has now been fixed in https://github.com/ImaginationForPeople/assembl/commit/358f4112b3a93be2032f0a9cf1d6ab5bafe65d80 :)

About develop versus master branch: http://nvie.com/posts/a-successful-git-branching-model/
The develop branch is where all development happens, it is normal if not everything works, it's constantly work in progress. When we are happy with its state and have tested it enough and did not find any major bug, we merge develop into master. So the master branch is the one which is recommended to use in production ;)

**Comment by jmatsushita** [comment]
That's good news! I think I'm already committed now to follow the develop branch with you. Given that I'm in a discovery phase with the tool it shouldn't be a problem for us. As I mentioned above in passing, you have setup your github with the develop branch as the default. It makes sense during development to avoid developers checking out the wrong branch, but its not a very standard setup and you might want to switch back to master as the default exactly for the reasons you mentioned! Will test the updates from yesterday now.

**Comment by maparent** [comment]
One last message on develop vs master: github is mostly for the development team, who uses develop on a daily basis. When we have packages, this will take the role of master.
