### ISSUE TITLE
Landing into discussions

### ISSUE THREAD

**Issue by jmatsushita** [ImaginationForPeople/assembl#14]
We had a chat about this in Brussels. Whatever is the lowest effort to help configure the discussion landing page, without re-inventing an html editor would really help to deal with the all important "first thing the user sees" when they are first laying eyes on an Assembl discussion.

The interesting thing I just realised is that as the instigator, because I get the About page first, it made me assume that this was also the page that regular users would see first but that not the case as they go straight to the Discussion. So maybe this needs to be made clearer.

We had discussed the option where the landing page really is somewhere else (in the instigators' CMS most probably) and help optimise the scenario of linking deep into discussions. Is that still the most likely path?

In our specific case (3 or 4 distinct but interlinked discussions inside one "assembl discussion") it is also useful to think of these "contained discussions" as having their own "landing pages" which could be outside of Assembl too.

In these cases where the "responsibility" for providing a nicely designed and explanatory landing page falls outside of the Assembl scope and into a CMS's scope, it might be useful to develop the conversation statistics and other interesting data to about the discussion, to be surfaced as embeddable widgets (or maybe they're accessible via an API already?). And in our specific case to help provide various "zoom" levels for these discussions, although that's certainly a "nice to have" level feature...

Cheers,

Jun

**Comment by benoitg** [comment]
Fixed in https://github.com/ImaginationForPeople/assembl/commit/57f3d238d674e9836d648bdc5832c90e23b2b5b2
