### ISSUE TITLE
install nodejs nodejs-legacy  is impossible

### ISSUE THREAD

**Issue by AlbertFR** [ImaginationForPeople/assembl#2]
On ubuntu 12.04 and 14.04
have a solution ?

**Comment by benoitg** [comment]
What's the error on 14.04?  The package is in the standard repository.

We didn't try 12.04 recently (an suspect you'd have other problems), but in that case you probably don't need the legacy package.

**Comment by AlbertFR** [comment]
the error is always here : 

Les paquets suivants contiennent des dépendances non satisfaites :
 nodejs : Est en conflit avec: nodejs-legacy
          Est en conflit avec: npm

**Comment by benoitg** [comment]
@AlbertFR I don't know what to tell you.  Our prod servers are on 14.04, and have all 3 packages installed (npm, nodejs, nodejs-legacy).  Several developers have 15.04, and it's the same thing.
