### ISSUE TITLE
Error after drag and drop of Idea

### ISSUE THREAD

**Issue by jmatsushita** [ImaginationForPeople/assembl#23]
If you are in contact with the technical team, please let them know about the following message:
url: /api/v1/discussion/2/ideas/18 ajax error message: Internal Server Error

**Comment by benoitg** [comment]
Not enough information, unless it's a public server.

**Comment by jmatsushita** [comment]
FYI It is a server accessible publicly, but I couldn't reproduce after updating, so it might have been related either to the ID 0 problem, or the permission problem which were both solved (one by creating another discussion and dodging the problem, the other with the latest commits)
