### ISSUE TITLE
Backup/Restore documentation.

### ISSUE THREAD

**Issue by jmatsushita** [ImaginationForPeople/assembl#26]
From gitter.

> swergas 12:54
> from your computer, to download locally the database of your server, type: fab remote_env database_download
> to overwrite your local database with the one you have downloaded, type fab local_env database_restore
> and Benoit has recently written a backup script: ImaginationForPeople/assembl@8f3b04c

**Comment by benoitg** [comment]
Documented in @8f3b04cfe8e7e771f7a5e1f099a68b51897e2f3c
