### ISSUE TITLE
Can't save Notifications changes

### ISSUE THREAD

**Issue by dachary** [ImaginationForPeople/assembl#30]
When changing the notifications from the page below, there is no way to save them.

![assembl](https://cloud.githubusercontent.com/assets/433594/15160989/95f6a19a-16fc-11e6-93dd-3480056d3392.png)

**Comment by ayyazdaniaryan** [comment]
Hi @dachary, checking/unchecking the the boxes should save the request. The immediate issue was resolved in 5956bc3b9d6920b64cda33e6f35805c6cb3192c2.

**Comment by ayyazdaniaryan** [comment]
There are other issues regarding this particular view that has now come to my attention. I will take them on in due time. However the current issue is resolved.

**Comment by dachary** [comment]
thanks!
