### ISSUE TITLE
docker build fails

### ISSUE THREAD

**Issue by dachary** [ImaginationForPeople/assembl#37]
The command `docker build --tag assembl docker` on 35319425fc27be4441559abaaa96a8e933a91d95 fails with

<pre>
....
[localhost] Executing task 'app_db_install'
[localhost] Executing task 'database_create'
[localhost] Executing task 'database_create_postgres'
[localhost] Executing task 'check_and_create_database_user'
[localhost] run: cd /opt/assembl && . /opt/assembl/venv/bin/activate && assembl-pypsql -1 -u assembl -p assembl -n localhost "SELECT 1 FROM pg_roles WHERE rolname='assembl'"
[localhost] out: mesg: ttyname failed: Inappropriate ioctl for device
[localhost] out: Traceback (most recent call last):
[localhost] out:   File "/opt/assembl/venv/bin/assembl-pypsql", line 9, in <module>
[localhost] out:     load_entry_point('assembl', 'console_scripts', 'assembl-pypsql')()
[localhost] out:   File "/opt/assembl/assembl/scripts/pypsql.py", line 22, in main
[localhost] out:     cx = psycopg2.connect(user=user, password=password, database=database, host=args.host)
[localhost] out:   File "/opt/assembl/venv/local/lib/python2.7/site-packages/psycopg2/__init__.py", line 164, in connect
[localhost] out:     conn = _connect(dsn, connection_factory=connection_factory, async=async)
[localhost] out: psycopg2.OperationalError: FATAL:  password authentication failed for user "assembl"
[localhost] out: FATAL:  password authentication failed for user "assembl"
[localhost] out: 
[localhost] out: 

Warning: run() received nonzero return code 1 while executing 'cd /opt/assembl && . /opt/assembl/venv/bin/activate && assembl-pypsql -1 -u assembl -p assembl -n localhost "SELECT 1 FROM pg_roles WHERE rolname='assembl'"'!

User does not exist
[localhost] sudo: . /opt/assembl/venv/bin/activate && assembl-pypsql -n localhost "CREATE USER assembl WITH CREATEDB ENCRYPTED PASSWORD 'assembl'"
[localhost] out: /bin/bash: /root/.bash_profile: Permission denied
[localhost] out: password: 
</pre>

**Comment by maparent** [comment]
Bien vu. Si tu as un moment sur gitter pour discuter stratégies de correction?

**Comment by dachary** [comment]
I successfully rebuilt on https://github.com/dachary/assembl/tree/wip-docker which is master from a few weeks ago (~14 may). I guess bisecting from there should work ;-)

**Comment by maparent** [comment]
I think I already understand the problem, I need advice on solutions.

**Comment by maparent** [comment]
ok I think I know

**Comment by maparent** [comment]
Solved that one. There is a problem downstream with secure connection, but that's a distinct issue.

**Comment by maparent** [comment]
Solved.

**Comment by dachary** [comment]
@maparent that was fast, thanks !
