### ISSUE TITLE
XSS VULNERABILITY zeroclipboard

### ISSUE THREAD

**Issue by denjello** [ImaginationForPeople/assembl#6]
zeroclipboard

What caught my eye is that it is kind of buggy in firefox 36.0.4 on debian with adblock edge. (The gif was made with screenshots without explicitly activating flash.)
![7](https://cloud.githubusercontent.com/assets/6129121/6983240/c40f3552-da1b-11e4-96ef-c212da24040e.gif)

After looking at the https://discussions.bluenove.com/static/js/bower/zeroclipboard/ZeroClipboard.js , it is clear that the version is pretty old (v1.2.3 vs. modern 2.2.0).

Furthermore, this version is affected by an XSS attack on the swf.
https://github.com/zeroclipboard/zeroclipboard/releases/tag/v1.3.2

**Comment by hellsingblack** [comment]
Thank you for your report we will update our version en test it in this case.

**Comment by benoitg** [comment]
We removed the dependency on Zeroclipboard. Thanks for the report.

**Comment by denjello** [comment]
good call.
